FROM nginx:alpine
ADD ./output/bundle.js /usr/share/nginx/html/bundle.js
ADD ./docker/index.html /usr/share/nginx/html/index.html
ADD ./src/images /usr/share/nginx/html/images
ADD ./src/favicon.ico /usr/share/nginx/html/
